import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import UploadImage from "../Components/UploadImage";
import ImageGallery from "../Components/SearchComponent";
import SearchComponent from "../Components/SearchComponent";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome find person by photo app :  </h1>

          <UploadImage/>

          <SearchComponent/>


      </main>
    </div>
  );
};

export default Home;
